-module(glorious_path).
-export([find/1]).

%% Returns the path generated by backingtracking score map.
%% 1st param -> 2-ple nucleotide Point.
%% 2nd param -> Scores of alignment.
%% 3rd param -> Path so far.
find_helper(Point, Scores, Path) ->
    case maps:get(Point, Scores) of
        {none, _} -> [Point|Path];
        {Next, _} -> find_helper(Next, Scores, [Point|Path])
    end.

%% Returns the path generated by backingtracking score map.
%% 1st param -> 2-ple with left|above|diagn and nucleotide Point.
%% 2nd param -> Scores of alignment.
find(NWResult) ->
    {Sequences, _, ScoreMap} = NWResult,
    Start = needleman_wunsch:last_point(Sequences),
    find_helper(Start, ScoreMap, []).
